version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'composer'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'daily'
