name: Test Extension
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: mkdir artifacts
      - run: npm install
      - name: Prettier
        run: npm run prettier-check
      - name: Lint
        run: npm run tslint
      - run: xvfb-run -a npm test
