on:
  release:
    types:
      - created

name: Upload the extension
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: mkdir artifacts
      - run: npm install
      - run: npm build
      - name: 'Release Extension'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/phpactor.vsix
          asset_name: phpactor.vsix
          asset_content_type: application/octet-stream
